/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

import co.edu.usbbog.datan.niote.controlador.logica.GestionRed;
import co.edu.usbbog.datan.niote.controlador.logica.ValidacionesSistema;

/**
 *
 * @author 305
 */
public class Principal extends javax.swing.JFrame {
    
    //relacion Logica
    private GestionRed gestionRed;
    private ValidacionesSistema validacionesSistema;
    
    //relaciones vista
    private Terminal terminal;
    
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.validacionesSistema = new ValidacionesSistema();
        this.terminal = new Terminal(this);
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Principal principal = new Principal();
    }

    public GestionRed getGestionRed() {
        return gestionRed;
    }

    public Terminal getTerminal() {
        return terminal;
    }
    
    public ValidacionesSistema getValidacionesSistema() {
        return validacionesSistema;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    protected boolean iniciarRed(String id, String nombre, String descripcion){
        this.gestionRed= new GestionRed(id, nombre, descripcion);
        if(this.gestionRed!=null){
            return true;
        }else{
            return false;
        }
    }

    protected boolean cargarRed(String ruta, String nombreArchivo) {
        //logica por impleentar 
        if(this.gestionRed!=null){
            return true;
        }else{
            return false;
        }
    }

   
}
